#!/usr/bin/env sh

if [[ $1 == "--user"]]; then
    uid="$2"
    shift 2
fi

if [[ $1 == "-u"]]; then
    uid="$2"
    shift 2
fi

usermod -u "$uid" erdpy > /dev/null
export PATH="/home/erdpy/elrondsdk:$PATH"

su erdpy -s /home/erdpy/elrondsdk/erdpy -- "$@"
